/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simple_myapplication_Test */

#ifndef _Included_simple_myapplication_Test
#define _Included_simple_myapplication_Test

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simple_myapplication_Test
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT void JNICALL
        Java_simple_myapplication_Convert_1C_CtoGrey(JNIEnv *env, jclass type, jintArray m_);
JNIEXPORT void JNICALL
        Java_simple_myapplication_Convert_1C_CpreDo(JNIEnv *env, jclass type, jintArray p1_,
                                                    jintArray p2_);
JNIEXPORT void JNICALL
        Java_simple_myapplication_Convert_1C_Ccomb(JNIEnv *env, jclass type, jintArray p1_, jintArray p2_);
#ifdef __cplusplus
}
#endif
#endif
