/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simple_myapplication_Test */

#ifndef _Included_simple_myapplication_Test
#define _Included_simple_myapplication_Test

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simple_myapplication_Test
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jstring JNICALL Java_simple_myapplication_Test_getInt
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL
        Java_simple_myapplication_Test_opArr(JNIEnv *env, jobject instance, jintArray a_);

#ifdef __cplusplus
}
#endif
#endif
